### ISSUE TITLE
example

### ISSUE THREAD

**Issue by lukeeey** [mhsjlw/RakLib#1]
better example? the current one doesnt work

**Comment by lukeeey** [comment]
@mhsjlw

**Comment by mhsjlw** [comment]
What exactly are you looking to do?

**Comment by lukeeey** [comment]
Well create a server software @mhsjlw

**Comment by mhsjlw** [comment]
Meet me in https://gitter.im/mhsjlw/RakNet

**Comment by mhsjlw** [comment]
The examples have been updated in https://github.com/mhsjlw/RakLib/commit/61c1ea3f7b44ae7e5d61e39d0257a4ea004668c1#diff-4d80ef3a92b9d8772168e65bfec25713
